import turtle
X=int(input('How many steps must a turtle walk down? '))
turtle.right(45)
turtle.forward(X)
turtle.right(90)
turtle.forward(X*2)
turtle.left(90)
turtle.forward(X)
turtle.left(90)
turtle.forward(X)
turtle.left(90)
turtle.forward(X*2)
turtle.right(90)
turtle.forward(X)
